name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v1
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: meeDamian/github-release@2.0
        with:
          prerelease: true
          draft: false
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # tag: latest
          name: My Creative Name
          body: >
            This release actually changes the fabric of the reality, so be careful 
            while applying, as error in database migration, can irrecoverably wipe 
            some laws of physics.  
          gzip: folders
          files: >
            README.md
            LICENSE.txt
            content.txt

