name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v1

      - name: Generate version 
        id: get-version
        run: |
          echo "::set-output name=basic::$(cat VERSION)"
          
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: meeDamian/github-release@2.0
        with:
          prerelease: true
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commitish: master
          tag: v${{ steps.get-version.outputs.basic }}
          name: Release v${{ steps.get-version.outputs.basic }}
          body: >
            This is release v${{ steps.get-version.outputs.basic }}, an unstable build.
          gzip: folders
          files: >
            LICENSE.txt
            content.txt
            README.md
