name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v1

      - name: Generate version 
        id: get-version
        run: |
          echo "::set-output name=basic::$(cat VERSION)"
          
      - name: "Build & test"
        run: |
          echo "done!"

      - name: git
        run: |
          set -x
          git remote -v
          git tag -f v${{ steps.get-version.outputs.basic }}-latest
          git push origin v${{ steps.get-version.outputs.basic }}-latest --force

